### ISSUE TITLE
Error when running plugin

### ISSUE THREAD

**Issue by shemreader** [ellisvalentiner/steampipe-plugin-confluence#57] opened 2024-06-11 07:59 UTC
Hi
I am trying to use confluence and i am getting the following error.
steampipe query "select * from confluence_content;"
Error: rpc error: code = Internal desc = hydrate function listContent failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
+----+-------+-----------+--------+------+----------------+------+
| id | title | space_key | status | type | version_number | _ctx |
+----+-------+-----------+--------+------+----------------+------+
+----+-------+-----------+--------+------+----------------+------+
any ideas why ?
Thanks

**Comment by ellisvalentiner** [comment] 2024-06-11 15:48
I'm not sure why you're getting that error but I can look at this next week.

Do you have any other logs you can share?

**Comment by e-gineer** [comment] 2024-06-11 16:01
@shemreader Do you get more information in `~/.steampipe/logs` if you try doing
```
export STEAMPIPE_LOG_LEVEL=debug
```

and then rerunning?

**Comment by ellisvalentiner** [comment] 2024-06-20 13:15
The logs appear to be exclusively about the grafana plugin, not this one.

I can't reproduce, so closing for now.
Happy to reopen if there is more info.

**Closed by ellisvalentiner** 2024-06-20 13:15 UTC
